target 'test-indra-peliculas' do
  use_frameworks!

  # Pods for test-indra-peliculas
  pod 'Alamofire'
  pod 'Kingfisher', '~> 7.0'

  target 'test-indra-peliculasTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
