# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'test-indra-peliculas' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for test-indra-peliculas
  pod 'Alamofire'
  pod 'Kingfisher', '~> 7.0'


  target 'test-indra-peliculasTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
